apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
- name: workspace41be73cc9318458d-sa-dockercfg-b7t6t
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: workspace41be73cc9318458d-sa-dockercfg-b7t6t
  labels:
    controller.devfile.io/devworkspace_id: workspace41be73cc9318458d
    controller.devfile.io/devworkspace_name: terminal-4g6jmi
  name: workspace41be73cc9318458d-sa
  ownerReferences:
  - apiVersion: workspace.devfile.io/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: DevWorkspace
    name: terminal-4g6jmi
    uid: 41be73cc-9318-458d-881d-2348ca6e42c3
secrets:
- name: workspace41be73cc9318458d-sa-dockercfg-b7t6t
